### ISSUE TITLE
Throwing Exception thrown: 'System.ComponentModel.Win32Exception' in mip_dotnet_api.dll

### ISSUE THREAD

**Issue by rajkumar4543** [Azure-Samples/MipSdk-Dotnet-File-Quickstart#4]
When I run the solution getting below error:
Exception thrown: 'System.ComponentModel.Win32Exception' in mip_dotnet_api.dll

**Comment by csharmath** [comment]
Try to change to platform target to x64 instead of AnyCPU

**Comment by tommoser** [comment]
Also ensure you've built the application in Release and have the Visual C++ redisttributable installed if you're running on a machine that isn't your dev machine.
