### ISSUE TITLE
A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

### ISSUE THREAD

**Issue by LiDamon** [Azure-Samples/MipSdk-Dotnet-File-Quickstart#7]
Throw Exception while my signed program
Could not load file or assembly 'mip_dotnet_api, Version=1.1.210.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

**Comment by tommoser** [comment]
Hi @LiDamon, I've filed a bug for this and will update as soon as we have it fixed.

**Comment by KaushalKhamar** [comment]
Hi @tommoser , Is this issue resolved? I am facing same issue while implementing Azure AIP in SharePoint.

**Comment by tommoser** [comment]
Sorry, not yet.

**Comment by KaushalKhamar** [comment]
Hey @tommoser ,

I have manually signed mip_dotnet_api dll. But still having same error as this dll reference to another unsigned dll dotnet_wrapper.dll. Can you please let me know what can i do next?

**
![image](https://user-images.githubusercontent.com/7072474/55883762-87b4c700-5bc4-11e9-9c48-ad2d619c421b.png)
**

**Comment by KaushalKhamar** [comment]
Hay @tommoser Any tentative date for releasing signed dlls for AIP?

**Comment by tommoser** [comment]
We are doing the work to update the build process in the next week or two. At that point, assuming all goes well, I plan to release an updated 1.2 build. At the latest, this will ship with our 1.3 release in July, but I expect that I'll be able to ship the updated NuGet package well before then.

**Comment by KaushalKhamar** [comment]
Hay @tommoser, Thanks for update. Appreciate your efforts. 👍

**Comment by tommoser** [comment]
Fixed in 1.3
